services:
  gateway:
    build: gateway
    ports:
      - "${GATEWAY_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./gateway
          target: /code
        - action: rebuild
          path: ./gateway/requirements.txt

  inventory:
    build: inventory
    ports:
      - "${INVENTORY_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./inventory
          target: /code
        - action: rebuild
          path: ./inventory/requirements.txt

  notification:
    build: notification
    ports:
      - "${NOTIFICATION_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./notification
          target: /code
        - action: rebuild
          path: ./notification/requirements.txt

  order:
    build: order
    ports:
      - "${ORDER_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./order
          target: /code
        - action: rebuild
          path: ./order/requirements.txt

  payment:
    build: payment
    ports:
      - "${PAYMENT_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./payment
          target: /code
        - action: rebuild
          path: ./payment/requirements.txt

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

volumes:
  db:
    driver: local